version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "uv"
    directory: "/aristaproto"
    schedule:
      interval: "monthly"

  - package-ecosystem: "uv"
    directory: "/aristaproto_compiler"
    schedule:
      interval: "monthly"
