---
version: 2
updates:
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directories:
      - "/"
    groups:
      prod:
        dependency-type: "production"
      dev:
        dependency-type: "development"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "Bump(requirements): "
      prefix-development: "CI(requirements):"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "CI: "
