ci:
  autofix_prs: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-format
        args: ["--diff", "aristaproto/src", "aristaproto/tests", "aristaproto_compiler/src", "aristaproto_compiler/tests"]
      - id: ruff
        args: ["aristaproto/src", "aristaproto/tests", "aristaproto_compiler/src", "aristaproto_compiler/tests"]

  - repo: https://github.com/bufbuild/buf
    rev: v1.71.0
    hooks:
      - id: buf-format
        files: ^aristaproto_compiler/tests/inputs/.*\.proto$
