# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobuf.proto
# plugin: python-aristaproto
# This file has been @generated

__all__ = ()


import aristaproto

_COMPILER_VERSION = "0.10.1"
aristaproto.check_compiler_version(_COMPILER_VERSION)
