name: Release

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  publish_aristaproto:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/lib-v')
    name: Publish aristaproto to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/aristaproto

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.11"
          python-version: "3.10"

      - name: Build package
        working-directory: ./aristaproto
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.14
        with:
          packages-dir: aristaproto/dist

  publish_aristaproto_compiler:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/compiler-v')
    name: Publish aristaproto_compiler to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/aristaproto_compiler

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.11"
          python-version: "3.10"

      - name: Build package
        working-directory: ./aristaproto_compiler
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.14
        with:
          packages-dir: aristaproto_compiler/dist
